// Nationwide grants directory — veteran, small business, tech/AI.
// Status values drive the colored badge in the UI.
// Last verified: 2026-04-09.

export type GrantStatus = 'OPEN' | 'ROLLING' | 'MONTHLY' | 'CLOSED' | 'OPENS_LATER' | 'COHORT';
export type GrantCategory = 'veteran' | 'small-business' | 'tech-ai' | 'women-minority';

export interface Grant {
  name: string;
  sponsor: string;
  amount: string;
  status: GrantStatus;
  deadline: string; // e.g. "Rolling", "Dec 15, 2025 (closed)", "Sep 2026 (est.)"
  eligibility: string;
  url: string;
  categories: GrantCategory[];
  notes?: string;
}

export const grants: Grant[] = [
  // ───────────────────────── VETERAN-FOCUSED ─────────────────────────
  {
    name: 'Hiring Our Heroes Small Business Grant',
    sponsor: 'U.S. Chamber of Commerce Foundation + FedEx',
    amount: '$10,000–$25,000',
    status: 'CLOSED',
    deadline: 'Next cycle expected late 2026',
    eligibility: 'Veteran- or military-spouse-owned, 3–20 employees, < $5M revenue',
    url: 'https://www.hiringourheroes.org/small-business-grant/',
    categories: ['veteran', 'small-business'],
    notes: '2026 cycle closed Dec 15, 2025. Winners announced ~Mar 29, 2026.',
  },
  {
    name: 'Stephen L. Tadlock Veteran Business Grant',
    sponsor: 'Founders First CDC',
    amount: '$1,000 × 25 awards',
    status: 'OPENS_LATER',
    deadline: 'Next cycle ~Sep 2026',
    eligibility: 'U.S. veteran, active employer-based biz, 2–100 employees, 1+ year in operation, < $5M revenue',
    url: 'https://foundersfirstcdc.org/stephen-tadlock',
    categories: ['veteran', 'small-business'],
  },
  {
    name: 'Warrior Rising / Warrior Academy',
    sponsor: 'Warrior Rising (501(c)(3))',
    amount: 'Up to $20,000 (program + pitch)',
    status: 'ROLLING',
    deadline: 'Rolling applications',
    eligibility: 'U.S. veteran or immediate family, for-profit business at any stage',
    url: 'https://warriorrising.org/become-vetrepreneur/',
    categories: ['veteran', 'small-business'],
    notes: 'Not a traditional grant — training-led with pitch funding downstream.',
  },
  {
    name: 'Second Service Foundation — Veteran Small Business Award',
    sponsor: 'Second Service Foundation (formerly StreetShares Foundation)',
    amount: '$5,000 / $3,000 / $2,000',
    status: 'MONTHLY',
    deadline: 'Monthly cycle',
    eligibility: 'Veteran or military-spouse-owned, for-profit, demonstrable military community impact',
    url: 'https://streetshares-foundation.squarespace.com/the-veteran-small-business-award',
    categories: ['veteran', 'small-business'],
  },
  {
    name: 'Military Entrepreneur Challenge (MEC)',
    sponsor: 'Second Service Foundation',
    amount: 'Pitch seed capital',
    status: 'ROLLING',
    deadline: 'Register + speed coaching, then pitch at event',
    eligibility: 'Veteran, military spouse, or Gold Star Family entrepreneur w/ social impact',
    url: 'https://secondservicefoundation.org/',
    categories: ['veteran', 'small-business'],
  },
  {
    name: 'SBA Veteran Business Outreach Center (VBOC)',
    sponsor: 'U.S. Small Business Administration',
    amount: 'Free support + grant referrals',
    status: 'ROLLING',
    deadline: 'Continuous',
    eligibility: 'Veterans, transitioning service members, spouses',
    url: 'https://www.sba.gov/business-guide/grow-your-business/veteran-owned-businesses',
    categories: ['veteran'],
  },
  {
    name: 'CalVet Veteran Business Ownership Program',
    sponsor: 'California Department of Veterans Affairs',
    amount: 'Certification + referral to grants',
    status: 'ROLLING',
    deadline: 'Continuous',
    eligibility: 'California veteran business owners',
    url: 'https://www.calvet.ca.gov/VetServices/Pages/Veteran-Business-Ownership.aspx',
    categories: ['veteran'],
  },
  {
    name: 'SoCal Veteran Business Outreach Center — Grant Portal',
    sponsor: 'SoCal VBOC',
    amount: 'Aggregator — $1k–$100k+',
    status: 'ROLLING',
    deadline: 'Varies',
    eligibility: 'Southern California veterans (most listings)',
    url: 'https://socalvboc.org/grants/',
    categories: ['veteran'],
  },
  {
    name: 'Bunker Labs / WeVets',
    sponsor: 'Institute for Veterans and Military Families',
    amount: 'Varies',
    status: 'OPENS_LATER',
    deadline: 'Next cycle ~Jan 2027',
    eligibility: 'Veteran and military-spouse entrepreneurs',
    url: 'https://bunkerlabs.org/',
    categories: ['veteran', 'small-business'],
  },
  {
    name: 'VetFran',
    sponsor: 'International Franchise Association',
    amount: 'Franchise fee discounts + programs',
    status: 'ROLLING',
    deadline: 'Continuous',
    eligibility: 'Veterans pursuing franchise ownership',
    url: 'https://www.vetfran.org/',
    categories: ['veteran', 'small-business'],
  },
  {
    name: 'Boots to Business',
    sponsor: 'SBA',
    amount: 'Free entrepreneurship training',
    status: 'ROLLING',
    deadline: 'Continuous',
    eligibility: 'Transitioning service members, veterans, spouses',
    url: 'https://sbavets.force.com/s/',
    categories: ['veteran'],
  },

  // ───────────────────── GENERAL SMALL BUSINESS ─────────────────────
  {
    name: 'Amber Grant for Women',
    sponsor: 'WomensNet',
    amount: '$10,000 monthly + $25,000 annual',
    status: 'MONTHLY',
    deadline: 'Monthly cycle',
    eligibility: 'Women-owned U.S. business',
    url: 'https://ambergrantsforwomen.com/',
    categories: ['small-business', 'women-minority'],
  },
  {
    name: 'Hello Alice Small Business Grants',
    sponsor: 'Hello Alice + corporate partners',
    amount: '$5,000–$50,000 (varies)',
    status: 'ROLLING',
    deadline: 'Rotating programs',
    eligibility: 'Varies by program (small business owners)',
    url: 'https://helloalice.com/grants/',
    categories: ['small-business'],
  },
  {
    name: 'Comcast RISE',
    sponsor: 'Comcast NBCUniversal',
    amount: '$5,000 monetary + marketing/tech services',
    status: 'OPEN',
    deadline: 'Rolling cohorts',
    eligibility: 'Small business owners; prior cycles prioritized BIPOC/women',
    url: 'https://www.comcastrise.com/',
    categories: ['small-business', 'women-minority'],
  },
  {
    name: 'FedEx Small Business Grant Contest',
    sponsor: 'FedEx',
    amount: 'Up to $50,000 + print/services',
    status: 'OPENS_LATER',
    deadline: 'Annual cycle (spring)',
    eligibility: 'U.S. small business, 6+ months in operation',
    url: 'https://smallbusinessgrant.fedex.com/',
    categories: ['small-business'],
  },
  {
    name: 'Visa Everywhere Initiative',
    sponsor: 'Visa',
    amount: 'Up to $100,000',
    status: 'COHORT',
    deadline: 'Annual global competition',
    eligibility: 'Fintech and commerce startups',
    url: 'https://usa.visa.com/partner-with-us/visa-consulting-analytics/visa-everywhere-initiative.html',
    categories: ['small-business', 'tech-ai'],
  },
  {
    name: 'Verizon Small Business Digital Ready Grant',
    sponsor: 'Verizon + LISC',
    amount: '$10,000',
    status: 'ROLLING',
    deadline: 'Rolling cohorts',
    eligibility: 'U.S. small business owners who complete Digital Ready curriculum',
    url: 'https://smallbusiness.verizon.com/resources/grants/',
    categories: ['small-business'],
  },
  {
    name: 'Backing Small Businesses — Accion Opportunity Fund',
    sponsor: 'Accion Opportunity Fund + American Express',
    amount: '$5,000 supplies grant / $25,000 enhancement grant',
    status: 'COHORT',
    deadline: 'Annual cycle',
    eligibility: 'Small businesses in underserved communities',
    url: 'https://www.aofund.org/',
    categories: ['small-business', 'women-minority'],
  },
  {
    name: 'NASE Growth Grant',
    sponsor: 'National Association for the Self-Employed',
    amount: 'Up to $4,000',
    status: 'ROLLING',
    deadline: 'Monthly review',
    eligibility: 'NASE members in good standing (membership required)',
    url: 'https://www.nase.org/become-a-member/member-benefits/nase-growth-grant',
    categories: ['small-business'],
  },
  {
    name: 'Venmo Small Business Grant',
    sponsor: 'Venmo / PayPal',
    amount: '$10,000 × 20 recipients',
    status: 'OPENS_LATER',
    deadline: 'Annual cycle (summer)',
    eligibility: 'U.S. small business using Venmo Business profile',
    url: 'https://venmo.com/small-business-grant',
    categories: ['small-business'],
  },

  // ───────────────────── TECH / AI / INNOVATION ─────────────────────
  {
    name: 'SBIR — Small Business Innovation Research',
    sponsor: 'U.S. federal agencies (11 participating)',
    amount: 'Phase I $50k–$275k, Phase II up to $1.7M+',
    status: 'ROLLING',
    deadline: 'Solicitations year-round by agency',
    eligibility: 'U.S. for-profit < 500 employees, 51%+ U.S. owned',
    url: 'https://www.sbir.gov/',
    categories: ['tech-ai', 'small-business'],
    notes: 'Best-in-class for R&D-heavy tech companies. Non-dilutive.',
  },
  {
    name: 'STTR — Small Business Technology Transfer',
    sponsor: 'U.S. federal agencies (5 participating)',
    amount: 'Phase I up to $275k, Phase II up to $1.7M',
    status: 'ROLLING',
    deadline: 'Solicitations year-round by agency',
    eligibility: 'Small business partnered w/ non-profit research institution',
    url: 'https://www.sbir.gov/about/about-sttr',
    categories: ['tech-ai', 'small-business'],
  },
  {
    name: 'AFWERX / SpaceWERX SBIR Open Topic',
    sponsor: 'U.S. Air Force / Space Force',
    amount: 'Phase I $75k, Phase II $1.25M, Phase III uncapped',
    status: 'ROLLING',
    deadline: 'Open topics release quarterly',
    eligibility: 'Small businesses w/ dual-use tech applicable to DoD',
    url: 'https://afwerx.com/',
    categories: ['tech-ai', 'veteran', 'small-business'],
    notes: 'Strong fit for veteran-founded tech companies — veteran status is a bonus, not required.',
  },
  {
    name: 'Army xTech',
    sponsor: 'U.S. Army',
    amount: 'Up to $1M+ in prize challenges',
    status: 'ROLLING',
    deadline: 'Challenge-based, year-round',
    eligibility: 'U.S. small business w/ tech solutions to Army problem statements',
    url: 'https://www.xtech.army.mil/',
    categories: ['tech-ai', 'small-business'],
  },
  {
    name: 'NSF America\'s Seed Fund (NSF SBIR/STTR)',
    sponsor: 'National Science Foundation',
    amount: 'Phase I $305k, Phase II $1M+',
    status: 'ROLLING',
    deadline: 'Two proposal windows per year',
    eligibility: 'U.S. deep-tech startups at TRL 3–7',
    url: 'https://seedfund.nsf.gov/',
    categories: ['tech-ai', 'small-business'],
  },
  {
    name: 'Google for Startups Founders Fund',
    sponsor: 'Google',
    amount: 'Up to $150k non-dilutive + cloud credits',
    status: 'COHORT',
    deadline: 'Rolling cohorts (Black, Latino, Women, AI-focused)',
    eligibility: 'Early-stage startups in cohort categories',
    url: 'https://startup.google.com/programs/founders-funds/',
    categories: ['tech-ai', 'women-minority'],
  },
  {
    name: 'Microsoft for Startups Founders Hub',
    sponsor: 'Microsoft',
    amount: 'Up to $150k Azure credits + OpenAI API credits',
    status: 'ROLLING',
    deadline: 'Continuous',
    eligibility: 'B2B software/AI startups, any stage',
    url: 'https://www.microsoft.com/en-us/startups',
    categories: ['tech-ai'],
    notes: 'Credits only, no cash — but direct Azure OpenAI access.',
  },
  {
    name: 'NVIDIA Inception',
    sponsor: 'NVIDIA',
    amount: 'Credits, discounts, GPU access, co-marketing',
    status: 'ROLLING',
    deadline: 'Continuous',
    eligibility: 'AI/ML startups',
    url: 'https://www.nvidia.com/en-us/startups/',
    categories: ['tech-ai'],
  },
  {
    name: 'AWS Activate',
    sponsor: 'Amazon Web Services',
    amount: 'Up to $100k AWS credits',
    status: 'ROLLING',
    deadline: 'Continuous',
    eligibility: 'Early-stage startups',
    url: 'https://aws.amazon.com/activate/',
    categories: ['tech-ai'],
  },
  {
    name: 'Founders First CDC — Job Creators Quest Grant',
    sponsor: 'Founders First CDC',
    amount: '$2,000–$25,000',
    status: 'OPENS_LATER',
    deadline: 'Quarterly cycles',
    eligibility: 'Underrepresented-founder-led service businesses w/ 2–20 employees',
    url: 'https://foundersfirstcdc.org/',
    categories: ['small-business', 'women-minority'],
  },
  {
    name: 'Tory Burch Foundation Fellows Program',
    sponsor: 'Tory Burch Foundation',
    amount: '$5,000 grant + capital + mentorship',
    status: 'OPENS_LATER',
    deadline: 'Annual (typically fall)',
    eligibility: 'Women entrepreneurs, 1–5 years in business',
    url: 'https://www.toryburchfoundation.org/programs/fellows-program/',
    categories: ['women-minority', 'small-business'],
  },
  {
    name: 'IFundWomen Universal Grant Application Database',
    sponsor: 'IFundWomen',
    amount: 'Aggregator — many programs',
    status: 'ROLLING',
    deadline: 'Apply once, matched continuously',
    eligibility: 'Women business owners',
    url: 'https://ifundwomen.com/grants',
    categories: ['women-minority', 'small-business'],
  },
  {
    name: 'digitalundivided BREAKTHROUGH',
    sponsor: 'digitalundivided + JPMorgan Chase',
    amount: '$5,000 grant + accelerator',
    status: 'COHORT',
    deadline: 'Annual cohort (Feb–Apr typical)',
    eligibility: 'Women-of-color founders w/ revenue-generating business',
    url: 'https://digitalundivided.com/breakthrough',
    categories: ['women-minority', 'small-business'],
  },
  {
    name: 'Grants.gov — Federal Grant Search',
    sponsor: 'U.S. federal government (aggregator)',
    amount: 'Varies',
    status: 'ROLLING',
    deadline: 'Varies per program',
    eligibility: 'Varies — filter by business type, state, NAICS',
    url: 'https://www.grants.gov/search-grants',
    categories: ['small-business', 'tech-ai', 'veteran'],
    notes: 'Canonical source for federal opportunities. Filter aggressively.',
  },
  {
    name: 'CalOSBA Small Business Grant Programs',
    sponsor: 'California Office of the Small Business Advocate',
    amount: '$5,000–$25,000+ (varies by program)',
    status: 'ROLLING',
    deadline: 'Varies per program',
    eligibility: 'California small businesses',
    url: 'https://calosba.ca.gov/',
    categories: ['small-business'],
  },
];

export const categoryLabels: Record<GrantCategory, string> = {
  veteran: 'Veteran-owned',
  'small-business': 'Small business',
  'tech-ai': 'Tech / AI / Innovation',
  'women-minority': 'Women / Minority',
};

export const statusMeta: Record<GrantStatus, { label: string; tone: string }> = {
  OPEN: { label: 'Open', tone: 'bg-green-100 text-green-800 border-green-200' },
  ROLLING: { label: 'Rolling', tone: 'bg-emerald-100 text-emerald-800 border-emerald-200' },
  MONTHLY: { label: 'Monthly', tone: 'bg-blue-100 text-blue-800 border-blue-200' },
  COHORT: { label: 'Cohort', tone: 'bg-purple-100 text-purple-800 border-purple-200' },
  OPENS_LATER: { label: 'Opens later', tone: 'bg-amber-100 text-amber-800 border-amber-200' },
  CLOSED: { label: 'Closed', tone: 'bg-gray-200 text-gray-700 border-gray-300' },
};
